### ISSUE TITLE
Support for Composer 2

### ISSUE THREAD

**Issue by aleksblendwerk** [mageops/php-composer-plugin-patchset#2]
Would be great to see support for Composer 2 added.

Currently `composer install` fails using Composer 2 because `composer-plugin-patchset` requires `composer-plugin-api ^1.1`.

**Comment by pinkeen** [comment]
Hey @aleksblendwerk sorry to be so late with the reply, I've missed this issue. 
On the bright side I've just released v3.0 with support for Composer 2.x 🎉.
