### ISSUE TITLE
External JSON file containing the patchset object

### ISSUE THREAD

**Issue by maurizio-kitroyale** [mageops/php-composer-plugin-patchset#4]
Hi team,

I'm paying around with the module trying to migrate to it from `cweagans/composer-patches` and I was wondering if there is an equivalent to their `patches-file` attribute.

The goal is to define the patches in the main composer.json [as per your documentation](https://github.com/mageops/php-composer-plugin-patchset/blob/master/docs/usage.md#define-patches-in-your-root-package) but still have them in a separate json file

Is that an option in the current project or something you are planning on adding?

Thanks

Maurizio

**Comment by diwipl** [comment]
Hi

What we do internally is, we have a separate package with patches files: https://github.com/magesuite/magento-patches

And then we have two types of patches:
- essential: they are put into above package composer.json and get installed globally every time you install above package
- optional: they are only installed when you put them into main composer.json of a specific project like this:
```
"extra": {
        "patchset": {
            "aheadworks/module-automatic-related-products": [
                {
                    "description": "Fixes something",
                    "filename": "vendor/creativestyle/magento-patches/optional/aheadworks/some-fix.patch",
                    "version-constraint": "*"
                }
            ]
       }
}
```
